### ISSUE TITLE
use("https://git.sr.ht/~leon_plickat/paige") - doesn't work

### ISSUE THREAD

**Issue by humphreylee** [uncomfyhalomacro/erudite-vim#7]
Thanks for sharing your nvim config. I'm new to vim. I tried/ copied your config.  When I do :PackerInstall, there is error to get "paige" plugin. Not sure if you encounter similar issue and what is your fix? Thanks.

**Comment by uncomfyhalomacro** [comment]
@humphreylee that is just a bug in packer. you may want to do `:PackerSync` again inside neovim. Another workaround is to clone paige into `$HOME/.local/share/nvim/site/pack/packer/start/paige`

Recently, I didnt experience that issue. 
![image](https://user-images.githubusercontent.com/66054069/151396130-bb9e5442-78b5-4df1-afad-1971ebace94f.png)

Maybe next time, I will add an install script in case no one wants to bother with bootstrapping but that will not be a priority for now

**Comment by humphreylee** [comment]
Thanks for your reply. Let me test it out.

**Comment by humphreylee** [comment]
Sorry for my ignorance. What do you mean by bootstrapping, i.e. what are those steps and its purposes? Thanks.

**Comment by humphreylee** [comment]
The issue happened on Windows. It is OK on Linux/Debian.

**Comment by uncomfyhalomacro** [comment]
> The issue happened on Windows. It is OK on Linux/Debian.

Ah yes. i tried my config on windows, windows just does not work that well with neovim *and* lua. If I were you, I will try to use WSL instead of running neovim natively on Windows.

Bootstrapping is installing all the stuff you need so the program will work. In this case, my config needs to install those stuff first (bootstrapping) so I can run my config properly later.

EDIT: I actually didnt touch neovim on windows ever since. I tried it last week and the issue youre having, i experienced it. sorry i remembered just now

**Comment by humphreylee** [comment]
For Windows, I don't have Admin account, thus no WSL setup.

**Comment by uncomfyhalomacro** [comment]
> For Windows, I don't have Admin account, thus no WSL setup.

just create one. it should be that easy i guess. Im going to close this since this is a windows problem and not of neovim or lua's. feel free to open another issue
